global:
  nodeEnv: staging
  ecrRegistry: 123456789.dkr.ecr.us-east-1.amazonaws.com
  image:
    tag: latest

namespace: safestream-staging

authService:
  replicas: 1
  minReplicas: 1
  maxReplicas: 3

videoService:
  replicas: 1
  minReplicas: 1
  maxReplicas: 3

messengerService:
  replicas: 1
  minReplicas: 1
  maxReplicas: 2

transcodingWorker:
  replicas: 2
  minReplicas: 1
  maxReplicas: 5
